/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const Activity: typeof import('react').Activity
  const Button: typeof import('@workspace/ui').Button
  const Card: typeof import('@workspace/ui').Card
  const CardAction: typeof import('@workspace/ui').CardAction
  const CardContent: typeof import('@workspace/ui').CardContent
  const CardDescription: typeof import('@workspace/ui').CardDescription
  const CardFooter: typeof import('@workspace/ui').CardFooter
  const CardHeader: typeof import('@workspace/ui').CardHeader
  const CardTitle: typeof import('@workspace/ui').CardTitle
  const Fragment: typeof import('react').Fragment
  const Input: typeof import('@workspace/ui').Input
  const Label: typeof import('@workspace/ui').Label
  const Link: typeof import('@tanstack/react-router').Link
  const Spinner: typeof import('@workspace/ui').Spinner
  const Suspense: typeof import('react').Suspense
  const cache: typeof import('react').cache
  const cacheSignal: typeof import('react').cacheSignal
  const createContext: typeof import('react').createContext
  const createRef: typeof import('react').createRef
  const forwardRef: typeof import('react').forwardRef
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const startTransition: typeof import('react').startTransition
  const toast: typeof import('sonner').toast
  const use: typeof import('react').use
  const useActionState: typeof import('react').useActionState
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEffect: typeof import('react').useEffect
  const useEffectEvent: typeof import('react').useEffectEvent
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useIsMobile: typeof import('../hooks/use-mobile').useIsMobile
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useMemo: typeof import('react').useMemo
  const useOptimistic: typeof import('react').useOptimistic
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useRouter: typeof import('@tanstack/react-router').useRouter
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
  const z: (typeof import("zod"))["z"]
}
